### ISSUE TITLE
Loon的YouTube去广告插件没有效果

### ISSUE THREAD

**Issue by Koooooda** [Centralmatrix3/Matrix-io#26]
Loon规则的YouTube去广告插件没有效果，quantumult x的YouTube去广告重写有效果
![IMG_0640](https://github.com/Centralmatrix3/Matrix-io/assets/42514996/858d49dc-c5b6-434d-915b-6fe18d2f4e03)

**Comment by Centralmatrix3** [comment]
你好！我在使用过程中插件完美生效的并无异常。没有生效检查一下是否开启了脚本、复写、MitM。是否安装了证书并信任

**Comment by Koooooda** [comment]
> 你好！我在使用过程中插件完美生效的并无异常。没有生效检查一下是否开启了脚本、复写、MitM。是否安装了证书并信任

开启脚本后一切正常了，感谢
