### ISSUE TITLE
dns泄露

### ISSUE THREAD

**Issue by 77160860** [Centralmatrix3/Matrix-io#39]
dns:
  enable: true
  nameserver:
    - https://1.1.1.1/dns-query
    - https://8.8.8.8/dns-query
    - 1.1.1.1
    - 8.8.8.8
  nameserver-policy:
    geosite:cn:
        - https://1.12.12.12/dns-query
        - https://223.5.5.5/dns-query
  proxy-server-nameserver:
    - https://1.12.12.12/dns-query
    - https://223.5.5.5/dns-query

这样设置成白名单，只有大陆境内的用大陆dns，其余全部用境外dns，更加有效且不损失速度。

搭配proxy-provider,更省心[快捷配置](https://wiki.metacubex.one/example/conf/)

**Comment by Centralmatrix3** [comment]
你好！配置中的DNS主要是给国内使用的。代理的交给远端处理了(代理服务器)。Clash.Meta的[DNS工作流程](https://wiki.metacubex.one/config/dns/diagram/)。[DNS泄露](https://community.nssurge.com/d/2233-ip)问题参考Surge作者的说明

**Comment by 77160860** [comment]
> 你好！配置中的DNS主要是给国内使用的。代理的交给远端处理了(代理服务器)。Clash.Meta的[DNS工作流程](https://wiki.metacubex.one/config/dns/diagram/)。[DNS泄露](https://community.nssurge.com/d/2233-ip)问题参考Surge作者的说明

这是针对clash系
